version: '3.5'

services:
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db  
    ports:
     - '27017:27017'

  db_postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - db_postgres

  server:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./package.json
    container_name: nest-server
    environment:
      - PORT=${NEST_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - MONGO_URI=${MONGO_URI}
    ports:
      - '${NEST_PORT}:3000'
    depends_on:
      - db_postgres
      - mongo
    volumes:
      - ./src:/app/src  
    networks:
      - db_postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db_postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  
    networks:
      - db_postgres

networks:
  db_postgres:
    driver: bridge

volumes:
  pgdata:      
  server_src: 
  pgadmin_data:
  mongo_data: 
    
